Name: chronos-api
Host: 0.0.0.0
Port: 4442

Redis:
  Address: redis:6379
  Password: o6ex6A9gTobFzmX3YM8IyOwA3ZAcYKOD
  DB: 0
  TTLSeconds: 300
  JitterSeconds: 1
  LockTTLSeconds: 10
  RetryMs: 50
  RetryMax: 20



Mongo:
  URI: mongodb://root:bMDhGwa14pDGeszab4c5y5WCLrSYnEbW@mongo:27017/?authSource=admin
  Database: chart
  Collections:
    Spot: spot
    Derivative: derivative
    Market: market

Injective:
  BaseURL: https://k8s.global.mainnet.chart.grpc-web.injective.network
  TimeoutMs: 10000

Cron:
  Enabled: true
  IntervalSec: 60

